name: Gerar cobrinha

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: szkkj
          token: ${{ secrets.GH_TOKEN }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Deploy para a branch output
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
